if (self.CavalryLogger) { CavalryLogger.start_js(["oZvGZqY"]); }

__d("useGroupsCometLeaveDialogEntrypoint_group.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"useGroupsCometLeaveDialogEntrypoint_group",selections:[{alias:null,args:null,kind:"ScalarField",name:"can_viewer_see_sole_admin_treatment",storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null}],type:"Group",abstractKey:null};e.exports=a}),null);
__d("GroupsCometEventLinkedGroupInviteDialogQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"4668200943196062",metadata:{},name:"GroupsCometEventLinkedGroupInviteDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("GroupsCometLeaveDialogQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3973100919439408",metadata:{},name:"GroupsCometLeaveDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("GroupsCometSoleAdminDialogPreloadQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"4729361307090605",metadata:{},name:"GroupsCometSoleAdminDialogPreloadQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("GroupsCometLeaveActionMenuItem_group$normalization.graphql",[],(function(a,b,c,d,e,f){"use strict";a={kind:"SplitOperation",metadata:{},name:"GroupsCometLeaveActionMenuItem_group$normalization",selections:[{alias:null,args:null,kind:"ScalarField",name:"can_viewer_see_sole_admin_treatment",storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null},{alias:null,args:[{kind:"Literal",name:"sentance_case",value:!0}],concreteType:"TextWithEntities",kind:"LinkedField",name:"leave_text",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"text",storageKey:null}],storageKey:"leave_text(sentance_case:true)"}]};e.exports=a}),null);
__d("GroupsCometManageNotificationsActionMenuItem_group$normalization.graphql",[],(function(a,b,c,d,e,f){"use strict";a={kind:"SplitOperation",metadata:{},name:"GroupsCometManageNotificationsActionMenuItem_group$normalization",selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null}]};e.exports=a}),null);
__d("CometCreationContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b=a.createContext({isDraft:!1});g["default"]=b}),98);
__d("useIsCreationPreview",["CometCreationContext","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useContext;function a(){var a=h(c("CometCreationContext"));return a.isDraft}g["default"]=a}),98);
__d("CometCreationPreviewPlaceholder.react",["react","useIsCreationPreview"],(function(a,b,c,d,e,f,g){"use strict";d("react");function a(a){var b=a.children,d=a.placeholder,e=a.shouldShowPlaceholder;e=e===void 0?!1:e;var f=c("useIsCreationPreview")();a=Object.prototype.hasOwnProperty.call(a,"stringValueToCheck")&&(a.stringValueToCheck==null||a.stringValueToCheck==="");return f&&(a||e)?d:b}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("CometEntityHeaderCoverMediaFooter.react",["CometRow.react","CometRowItem.react","react","stylex"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react"),i={footer:{paddingBottom:"ihqw7lf3",paddingTop:"discj3wi",position:"l9j0dhe7"}};function a(a){var b=a.customBackgroundColor,d=a.footer,e=a.footerAlign;a=a.xstyle;return d==null?null:h.jsx("div",{className:c("stylex")(i.footer,a),style:{backgroundColor:b},children:h.jsx(c("CometRow.react"),{align:e,paddingHorizontal:16,paddingTop:0,verticalAlign:"bottom",children:h.jsx(c("CometRowItem.react"),{expanding:!0,children:d})})})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("CometEntityHeaderTitleRow.react",["react","stylex"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react");function a(a){var b=a.actorBlock,d=a.hasExtraSpace;d=d===void 0?!1:d;a=a.titleBlock;return b!=null?h.jsxs("div",{className:"j83agx80 aovydwv3",children:[h.jsx("div",{className:c("stylex").dedupe({"align-items-1":"aovydwv3","display-1":"j83agx80","height-1":"do00u71z","margin-bottom-1":"fi9g468h","margin-end-1":"wkznzc2l"},d?{"height-1":"datstx6m"}:null),children:h.jsx("div",{children:b})}),h.jsx("div",{className:"tr9rh885",children:a})]}):h.jsx("div",{className:"tr9rh885",children:a})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("CometEntityHeaderTopRow.react",["CometEntityHeaderTitleRow.react","CometRow.react","CometRowItem.react","react","stylex"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react"),i={auxiliaryColumn:{justifyContent:"bkfpd7mw"},column:{flexBasis:"rj1gh0hx",flexGrow:"dtpq6qua",minWidth:"p01isnhg"},columnBottomSpacing:{paddingBottom:"ihqw7lf3"},columnNoExpanding:{flexBasis:"mg4g778l",flexGrow:"buofh1pr"},root:{width:"k4urcfbm"},rootWithExtraSpace:{marginTop:"tr9rh885"}};function a(a){var b=a.actor,d=a.auxiliary,e=a.columnExpanding;e=e===void 0?!0:e;var f=a.hasExtraSpace;f=f===void 0?!1:f;var g=a.skipBottomSpacing;g=g===void 0?!1:g;a=a.titleBlock;return h.jsx("div",{className:c("stylex")(i.root,f&&i.rootWithExtraSpace),children:h.jsxs(c("CometRow.react"),{paddingHorizontal:0,verticalAlign:"bottom",wrap:"forward",children:[h.jsx(c("CometRowItem.react"),{expanding:!0,xstyle:[i.column,!g&&i.columnBottomSpacing],children:h.jsx(c("CometEntityHeaderTitleRow.react"),{actorBlock:b,titleBlock:a})}),h.jsx(c("CometRowItem.react"),{expanding:e,xstyle:[i.column,!e&&i.columnNoExpanding,!g&&i.columnBottomSpacing,i.auxiliaryColumn],children:d})]})})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("GroupsCometLeaveDialog.entrypoint",["GroupsCometLeaveDialogQuery$Parameters","JSResourceForInteraction"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){a=a.groupID;return{queries:{queryReference:{parameters:c("GroupsCometLeaveDialogQuery$Parameters"),variables:{groupID:a}}}}},root:c("JSResourceForInteraction")("GroupsCometLeaveDialog.react").__setRef("GroupsCometLeaveDialog.entrypoint")};g["default"]=a}),98);
__d("GroupsCometSoleAdminDialog.entrypoint",["GroupsCometSoleAdminDialogPreloadQuery$Parameters","JSResourceForInteraction","WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){a=a.groupID;return{queries:{queryReference:{parameters:c("GroupsCometSoleAdminDialogPreloadQuery$Parameters"),variables:{groupID:a,scale:d("WebPixelRatio").get()}}}}},root:c("JSResourceForInteraction")("GroupsCometSoleAdminDialog.react").__setRef("GroupsCometSoleAdminDialog.entrypoint")};g["default"]=a}),98);
__d("useGroupsCometLeaveDialogEntrypoint",["CometRelay","GroupsCometLeaveDialog.entrypoint","GroupsCometSoleAdminDialog.entrypoint","useGroupsCometLeaveDialogEntrypoint_group.graphql","useNullthrowsViolation"],(function(a,b,c,d,e,f,g){"use strict";var h;function a(a,e,f,g){a=d("CometRelay").useFragment(h!==void 0?h:h=b("useGroupsCometLeaveDialogEntrypoint_group.graphql"),a);var i=c("useNullthrowsViolation")(a==null?void 0:a.id);return(a==null?void 0:a.can_viewer_see_sole_admin_treatment)===!0?[c("GroupsCometSoleAdminDialog.entrypoint"),{groupID:i},{actionSource:e,onCancelLeave:g,onConfirmLeave:f,trigger:"LEAVE_GROUP"}]:[c("GroupsCometLeaveDialog.entrypoint"),{groupID:i},{actionSource:e,onCancelLeave:g,onConfirmLeave:f}]}g["default"]=a}),98);
__d("GroupsCometCreatePreviewContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b={isPreview:!1};c=a.createContext(b);g["default"]=c}),98);
__d("GroupsCometCreatePreviewDisabledWrapper.react",["GroupsCometCreatePreviewContext","react","stylex","useIsDarkMode"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react"),i=d("react").useContext;function a(a){var b=a.children;a=a.hasPreviewData;a=a===void 0?!1:a;var d=c("useIsDarkMode")(),e=i(c("GroupsCometCreatePreviewContext"));e=e.isPreview;e=e===void 0?!1:e;return h.jsx("div",{className:c("stylex").dedupe(e&&!a&&d?{"filter-1":"l880q9ns"}:{},e&&!a&&!d?{"filter-1":"flc5ov9u"}:null),children:b})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("GroupsCometEventLinkedGroupInviteDialog.entrypoint",["GroupsCometEventLinkedGroupInviteDialogQuery$Parameters","JSResourceForInteraction","WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){var b=a.eventID,e=a.groupID;a=a.source;return{queries:{queryReference:{options:{fetchPolicy:"network-only"},parameters:c("GroupsCometEventLinkedGroupInviteDialogQuery$Parameters"),variables:{eventID:b,groupID:e,scale:d("WebPixelRatio").get(),source:a}}}}},root:c("JSResourceForInteraction")("GroupsCometEventLinkedGroupInviteDialog.react").__setRef("GroupsCometEventLinkedGroupInviteDialog.entrypoint")};g["default"]=a}),98);
__d("range",[],(function(a,b,c,d,e,f){function a(a,b,c){c=c==null||c===0?a<b?1:-1:c;var d=-1;b=Math.max(Math.ceil((b-a)/c),0);var e=Array(b);a=a;while(b--)e[++d]=a,a+=c;return e}f["default"]=a}),66);
__d("GroupLeadersEngagementFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1743660");c=b("FalcoLoggerInternal").create("group_leaders_engagement",a);e.exports=c}),null);